/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.BackgroundPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.*;
import javax.swing.*;


/**
 *
 * @author ASUS
 */
public class Dashboard_Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName());
    private JPanel originalDashboardContent; // To store the Over-view UI
private Model.DrugModel drugModel = new Model.DrugModel();
private Controller.DrugController controller = new Controller.DrugController(drugModel);

    /**
     * Creates new form Dashboard_Admin
     */
    public Dashboard_Admin() {
        initComponents();
        customizeDashboard();
        originalDashboardContent = jPanel1;

    }
    
    public Dashboard_Admin(Controller.DrugController controller) {
        this.controller = controller;
        initComponents();
        customizeDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

private void setupBackgroundLayer() {

    Image bgImage = loadBackgroundImage("/images/login.png");
    if (bgImage == null) return;

    BackgroundPanel bgPanel = new BackgroundPanel(bgImage);
    bgPanel.setLayout(new BorderLayout());

    // Save current main content
    Container oldContent = getContentPane();

    // Replace frame content
    setContentPane(bgPanel);

    // Re-add your existing panels
    bgPanel.add(dashboard_Sidepannel, BorderLayout.WEST);
    bgPanel.add(jPanel1, BorderLayout.CENTER);

    // Make all panels transparent
    makePanelsTransparent(dashboard_Sidepannel);
    makePanelsTransparent(jPanel1);

    revalidate();
    repaint();
}

private void makePanelsTransparent(Container container) {
    for (Component c : container.getComponents()) {
        if (c instanceof JPanel) {
            ((JPanel) c).setOpaque(false);
            makePanelsTransparent((Container) c);
        }
    }
}

private Image loadBackgroundImage(String path) {
    java.net.URL url = getClass().getResource(path);
    if (url == null) {
        System.err.println("Background image not found: " + path);
        return null;
    }
    return new ImageIcon(url).getImage();
}

private void customizeDashboard() {
    // 1. Global Styling
    this.getContentPane().setBackground(new Color(15, 25, 30)); 
    UIManager.put("TitledBorder.font", new Font("SansSerif", Font.BOLD, 18));
    UIManager.put("TitledBorder.titleColor", new Color(0, 255, 255));
    
    // 2. Setup the main grid (jPanel1 is usually the main container in your file)
    // If your center area is jPanel21, keep it, otherwise use jPanel1
    jPanel21.removeAll();
    jPanel21.setLayout(new java.awt.GridBagLayout());
    jPanel21.setOpaque(false);

    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    gbc.insets = new java.awt.Insets(12, 12, 12, 12);
    gbc.fill = java.awt.GridBagConstraints.BOTH;

    // --- ROW 0 ---
    // Top Left: Sales/Product Table (Live View)
    gbc.gridx = 0; gbc.gridy = 0;
    gbc.weightx = 0.65; gbc.weighty = 0.5;
    jPanel21.add(createTopSalesPanel(), gbc);

    // Top Right: Summary Cards (Live Totals)
    gbc.gridx = 1; gbc.gridy = 0;
    gbc.weightx = 0.35; gbc.weighty = 0.5;
    jPanel21.add(createSummaryPanel(), gbc);

    // --- ROW 1 ---
    // Bottom Left: Calendar
    gbc.gridx = 0; gbc.gridy = 1;
    gbc.weightx = 0.65; gbc.weighty = 0.5;
    jPanel21.add(createCalendarPanel(), gbc);

    // Bottom Right: Payment & Progress 
    gbc.gridx = 1; gbc.gridy = 1;
    gbc.weightx = 0.35; gbc.weighty = 0.5;
    JPanel rightColumnBottom = new JPanel(new GridLayout(2, 1, 0, 15));
    rightColumnBottom.setOpaque(false);
    rightColumnBottom.add(createPaymentPanel());
    rightColumnBottom.add(createProgressPanel());
    jPanel21.add(rightColumnBottom, gbc);

    jPanel21.revalidate();
    jPanel21.repaint();
}
private JPanel createGlassPanel() {
    return new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new Color(20, 40, 50, 200)); 
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
            g2.setColor(new Color(0, 255, 255, 120));
            g2.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
            g2.dispose();
        }
    };
}

private JPanel createSummaryPanel() {
    // Reduced height container
    JPanel container = new JPanel(new GridLayout(1, 2, 10, 0));
    container.setOpaque(false);
    container.setPreferredSize(new Dimension(300, 100)); // Constrain the size

    container.add(createStyledCard("/images/basket.png", "Sales", "100,000 pcs"));
    container.add(createStyledCard("/images/money_bag.png", "Earning", "RS. 30,000"));

    return container;
}
private JPanel createStyledCard(String iconPath, String title, String value) {
    JPanel card = createGlassPanel();
    card.setLayout(new BorderLayout(8, 0));
    card.setBorder(BorderFactory.createEmptyBorder(8, 12, 8, 12));

    // Smaller icon for a more compact "Earning/Sales" look
    JLabel iconLabel = new JLabel(loadAndScaleImage(iconPath, 25, 25));
    
    JPanel textPanel = new JPanel();
    textPanel.setLayout(new BoxLayout(textPanel, BoxLayout.Y_AXIS));
    textPanel.setOpaque(false);

    JLabel titleLabel = new JLabel(title);
    titleLabel.setFont(new Font("SansSerif", Font.PLAIN, 11));
    titleLabel.setForeground(new Color(180, 180, 180));

    JLabel valueLabel = new JLabel(value);
    valueLabel.setFont(new Font("SansSerif", Font.BOLD, 14));
    valueLabel.setForeground(Color.CYAN);

    textPanel.add(Box.createVerticalGlue());
    textPanel.add(titleLabel);
    textPanel.add(valueLabel);
    textPanel.add(Box.createVerticalGlue());

    card.add(iconLabel, BorderLayout.WEST);
    card.add(textPanel, BorderLayout.CENTER);

    return card;
}
private JPanel createPaymentPanel() {
    JPanel panel = createGlassPanel();
    panel.setLayout(new BorderLayout());
    panel.setBorder(BorderFactory.createTitledBorder("Payment"));
    
    // Initialize the modified PieChart class
    model.PieChart pieChart = new model.PieChart();
    
    // Optional: Set custom data to override dummy data
    double[] values = {65, 35};
    String[] labels = {"Retail", "Wholesale"};
    Color[] colors = {new Color(0, 255, 255), new Color(150, 150, 150)};
    pieChart.setData(values, labels, colors);

    // Add to the glass panel
    panel.add(pieChart, BorderLayout.CENTER);
    
    return panel;
}

@Override
public void setVisible(boolean b) {
    // Styling the sidebar specifically to prevent it from stretching
    dashboard_Sidepannel.setPreferredSize(new Dimension(200, 0));
    dashboard_Sidepannel.setBackground(new Color(10, 20, 25));
    
    Component[] sideComps = dashboard_Sidepannel.getComponents();
    for (Component c : sideComps) {
        if (c instanceof JPanel) {
            ((JPanel) c).setOpaque(false);
            for (Component inner : ((JPanel) c).getComponents()) {
                if (inner instanceof JButton) {
                    JButton btn = (JButton) inner;
                    btn.setFont(new Font("SansSerif", Font.BOLD, 14));
                    btn.setForeground(Color.WHITE);
                    btn.setHorizontalAlignment(SwingConstants.LEFT);
                }
            }
        }
    }
    super.setVisible(b);
}

private JPanel createProgressPanel() {
    JPanel panel = createGlassPanel();
    panel.setLayout(new BorderLayout());
    panel.setBorder(BorderFactory.createTitledBorder("Progress Bar"));
    
    JPanel chart = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            
            int w = getWidth();
            int h = getHeight();
            
            // Draw background grid for readability
            g2.setColor(new Color(255, 255, 255, 20));
            for(int i = 1; i <= 4; i++) {
                int lineY = h - (i * h / 5);
                g2.drawLine(40, lineY, w - 20, lineY);
            }

            // Draw the Cyan Line Graph
            g2.setColor(new Color(0, 255, 255)); 
            g2.setStroke(new BasicStroke(2.5f));
            int[] x = {40, w/4, w/2, 3*w/4, w-30};
            int[] y = {h-50, h-90, h-70, h-120, h-80};
            
            for(int i=0; i < x.length - 1; i++) {
                g2.drawLine(x[i], y[i], x[i+1], y[i+1]);
                g2.fillOval(x[i]-3, y[i]-3, 6, 6);
            }
            g2.fillOval(x[x.length-1]-3, y[y.length-1]-3, 6, 6);
            g2.dispose();
        }
    };
    chart.setOpaque(false);
    panel.add(chart, BorderLayout.CENTER);
    return panel;
}
private JPanel createTopSalesPanel() {
    JPanel panel = createGlassPanel();
    panel.setLayout(new BorderLayout());
    panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Top Sales"));

    String[] columns = {"Drugs Name", "Stock", "Nickname", "Sales"};
    Object[][] data = {
        {"Giacomo Guizzon", 40, "Peldi", 500},
        {"Marco Botton", 38, "Rayoti", 20},
        {"Tuttofare", 41, "Patata", 800}
    };

    JTable table = new JTable(data, columns);
    table.setBackground(new Color(30, 50, 60));
    table.setForeground(Color.WHITE);
    table.setGridColor(new Color(0, 255, 255, 40));
    table.setRowHeight(25);
    
    JScrollPane scroll = new JScrollPane(table);
    scroll.setOpaque(false);
    scroll.getViewport().setOpaque(false);
    panel.add(scroll, BorderLayout.CENTER);

    return panel;
}

private JPanel createCalendarPanel() {
    JPanel panel = createGlassPanel();
    panel.setLayout(new BorderLayout());
    
    // 1. Get Current Month and Year for the title
    java.util.Calendar cal = new java.util.GregorianCalendar();
    String monthName = new java.text.SimpleDateFormat("MMMM YYYY").format(cal.getTime());
    panel.setBorder(BorderFactory.createTitledBorder(null, monthName, 
            javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    // 2. Setup Columns and Date Logic
    String[] columns = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};
    Object[][] days = new Object[6][7]; // 6 rows to handle all month layouts
    
    cal.set(java.util.Calendar.DAY_OF_MONTH, 1);
    int startDay = cal.get(java.util.Calendar.DAY_OF_WEEK) - 1;
    int maxDay = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);

    for (int day = 1, row = 0, col = startDay; day <= maxDay; day++) {
        days[row][col] = day;
        col++;
        if (col == 7) {
            col = 0;
            row++;
        }
    }

    // 3. Create and Style the JTable
    JTable calendarTable = new JTable(days, columns);
    calendarTable.setBackground(new Color(30, 50, 60));
    calendarTable.setForeground(Color.WHITE);
    calendarTable.setRowHeight(35);
    calendarTable.setGridColor(new Color(0, 255, 255, 30));
    calendarTable.setShowGrid(true);
    calendarTable.setEnabled(false); // Make it read-only
    calendarTable.setFont(new Font("SansSerif", Font.PLAIN, 14));

    // 4. Center the Text in Cells
    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
    centerRenderer.setOpaque(false); // Maintain glass look
    for (int i = 0; i < calendarTable.getColumnCount(); i++) {
        calendarTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    // 5. Style the Table Header (Sun, Mon, etc.)
    calendarTable.getTableHeader().setBackground(new Color(20, 40, 50));
    calendarTable.getTableHeader().setForeground(Color.CYAN);
    calendarTable.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
    calendarTable.getTableHeader().setBorder(BorderFactory.createLineBorder(new Color(0, 255, 255, 50)));

    // 6. Final Layout Assembly
    JScrollPane scroll = new JScrollPane(calendarTable);
    scroll.setOpaque(false);
    scroll.getViewport().setOpaque(false);
    scroll.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5)); // Add padding
    
    panel.add(calendarTable.getTableHeader(), BorderLayout.NORTH); // Manually add header for cleaner look
    panel.add(scroll, BorderLayout.CENTER);
    
    return panel;
}
private ImageIcon loadAndScaleImage(String path, int maxWidth, int maxHeight) {
    java.net.URL imgUrl = getClass().getResource(path);
    if (imgUrl == null) {
        System.err.println("Resource not found: " + path);
        return null;
    }
    
    ImageIcon icon = new ImageIcon(imgUrl);
    Image img = icon.getImage();

    int w = img.getWidth(null);
    int h = img.getHeight(null);

    if (w <= 0 || h <= 0) {
        System.err.println("Invalid image dimensions.");
        return icon;
    }

    double ratio = Math.min((double) maxWidth / w, (double) maxHeight / h);
    int newW = (int) (w * ratio);
    int newH = (int) (h * ratio);

    Image scaledImg = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
    return new ImageIcon(scaledImg);
}

private void refreshPanel() {
    jPanel1.revalidate();
    jPanel1.repaint();
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard_Sidepannel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drugs Management System");
        setMinimumSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        dashboard_Sidepannel.setBackground(new java.awt.Color(0, 255, 204));
        dashboard_Sidepannel.setForeground(new java.awt.Color(51, 255, 204));
        dashboard_Sidepannel.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        dashboard_Sidepannel.setOpaque(false);
        dashboard_Sidepannel.setPreferredSize(new java.awt.Dimension(200, 300));

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 89));

        jButton1.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jButton1.setText("DMS");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        dashboard_Sidepannel.add(jPanel9);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 89));

        jButton2.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jButton2.setText("Dashboard");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        dashboard_Sidepannel.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 89));

        jButton3.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jButton3.setText("Products");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboard_Sidepannel.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 89));

        jButton4.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jButton4.setText("Inventory");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboard_Sidepannel.add(jPanel6);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 89));

        jButton5.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jButton5.setText("History");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboard_Sidepannel.add(jPanel8);

        getContentPane().add(dashboard_Sidepannel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));

        jPanel14.setOpaque(false);

        jLabel7.setIcon(loadAndScaleImage("/images/logo3.png", 30, 35));
        jLabel7.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("i");

        jButton6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Profile");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Over-view");

        jPanel21.setBackground(new java.awt.Color(255, 153, 153));
        jPanel21.setOpaque(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.setMaximumSize(new java.awt.Dimension(200, 400));
        jPanel11.setPreferredSize(new java.awt.Dimension(274, 200));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// This is the "Dashboard" button
    jPanel1.removeAll(); // Or jPanel21 depending on your design
    jPanel1.setLayout(new BorderLayout()); 
    
    // This re-runs the code above, fetching fresh data from the controller
    customizeDashboard(); 
    
    // Add the refreshed grid back to the main container
    jPanel1.add(jPanel21, BorderLayout.CENTER);
    
    jPanel1.revalidate();
    jPanel1.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    jPanel1.removeAll();
    jPanel1.setLayout(new BorderLayout());
    Inventory inv = new Inventory(this.controller); 
    jPanel1.add(inv, BorderLayout.CENTER);
    jPanel1.revalidate();
    jPanel1.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jPanel1.removeAll();
    jPanel1.setLayout(new BorderLayout());
    
    // Pass the controller that is already defined in Dashboard_Admin
    ProductEntryForm entryForm = new ProductEntryForm(this.controller); 
    
    jPanel1.add(entryForm, BorderLayout.CENTER);
    
    // Refresh the UI
    jPanel1.revalidate();
    jPanel1.repaint();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard_Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboard_Sidepannel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
