/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Model.History;
import Model.SalesModel;
import Controller.DrugController;

/**
 *
 * @author ASUS
 */
public class Products extends javax.swing.JPanel {
    private Controller.DrugController controller;
    private javax.swing.JButton btnGrid;
    private Model.SalesModel salesModel;
    private Model.History historyModel;
    private Dashboard_Admin mainDashboard;

    /**
     * Creates new form Sales
     */
    
    private void styleInventory() {
        this.setOpaque(false);
        jLabel1.setForeground(new Color(0, 255, 255)); // Cyan
        jTable1.setBackground(new Color(30, 50, 60));
        jTable1.setForeground(Color.WHITE);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
    }

    public void loadData(Controller.DrugController controller) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear dummy rows
        
        // Loop through the ArrayList via the controller
        for (Model.Drug d : controller.getDrugs()) {
            model.addRow(new Object[]{d.getName(), d.getStock(), d.getVendor(), d.getUnitCost()});
        }
    }
    
    public Products() {
        initComponents();
       styleInventory();
       loadData(controller);
    }
    
public Products(DrugController controller, SalesModel salesModel, History historyModel, Dashboard_Admin dashboard) {
    this.controller = controller;
    this.salesModel = salesModel;
    this.historyModel = historyModel;
    this.mainDashboard = dashboard; // Store the reference
    initComponents();
    styleInventory();
    loadData(controller);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Products");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Stocks", "Vendor", "Unit Cost"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        jButton5.setText("Add Sales");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Sales Mode");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(131, 131, 131)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a row to update.");
        return;
    }

    try {
        // Show input dialogs for new values (Simplified for now)
        String newName = JOptionPane.showInputDialog(this, "Enter New Name:", jTable1.getValueAt(selectedRow, 0));
        String newStockStr = JOptionPane.showInputDialog(this, "Enter New Stock:", jTable1.getValueAt(selectedRow, 1));
        String newVendor = JOptionPane.showInputDialog(this, "Enter New Vendor:", jTable1.getValueAt(selectedRow, 2));
        String newCostStr = JOptionPane.showInputDialog(this, "Enter New Cost:", jTable1.getValueAt(selectedRow, 3));

        // --- VALIDATION ---
        if (newName == null || newName.trim().isEmpty()) throw new Exception("Name cannot be empty.");
        
        int newStock = Integer.parseInt(newStockStr);
        if (newStock < 0) throw new Exception("Stock cannot be negative.");
        
        double newCost = Double.parseDouble(newCostStr);
        if (newCost <= 0) throw new Exception("Cost must be greater than zero.");

        // Update via controller
        controller.editDrug(selectedRow, newName, newStock, newVendor, newCost);
        loadData(controller); // Refresh Table
        JOptionPane.showMessageDialog(this, "Update successful!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Please enter valid numbers for stock and cost.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Validation Error", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int[] selectedRows = jTable1.getSelectedRows();
    
    if (selectedRows.length == 0) {
        JOptionPane.showMessageDialog(this, "Please select one or more products to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete " + selectedRows.length + " item(s)?", 
        "Confirm Delete", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Sort indices to ensure we delete from highest index to lowest
        java.util.Arrays.sort(selectedRows);
        
        for (int i = selectedRows.length - 1; i >= 0; i--) {
            // Convert view index to model index in case the table is sorted
            int modelIndex = jTable1.convertRowIndexToModel(selectedRows[i]);
            controller.removeDrug(modelIndex); 
        }
        
        loadData(controller); 
        JOptionPane.showMessageDialog(this, "Items deleted successfully.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  String keyword = jTextField1.getText().trim();
    
    if (keyword.isEmpty()) {
        loadData(controller); // Reset to full list if empty
        return;
    }

    // Call your existing LinearSearch logic
    java.util.ArrayList<Model.Drug> results = Controller.LinearSearch.search(controller.getModel(), keyword);
    
    // Populate table with results
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    for (Model.Drug d : results) {
        model.addRow(new Object[]{d.getName(), d.getStock(), d.getVendor(), d.getUnitCost()});
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product first.");
        return;
    }

    int modelIndex = jTable1.convertRowIndexToModel(selectedRow);
    Model.Drug selectedDrug = controller.getDrugs().get(modelIndex);

    String qtyStr = JOptionPane.showInputDialog(this, "Enter quantity to sell:", "1");
    try {
        int qty = Integer.parseInt(qtyStr);
        if (qty <= 0) throw new Exception("Quantity must be positive.");
        
        if (selectedDrug.getStock() >= qty) {
            // FIX: Instead of calling controller.editDrug (which might create a new object without a picture),
            // simply update the stock on the existing object that already has the picture path.
            selectedDrug.setStock(selectedDrug.getStock() - qty);
            
            // Add to Sales Model
            for (int i = 0; i < qty; i++) {
                salesModel.addToSales(selectedDrug);
            }
            
            loadData(controller); // Refresh Table
            JOptionPane.showMessageDialog(this, qty + " units of " + selectedDrug.getName() + " added to sales queue.");
        } else {
            JOptionPane.showMessageDialog(this, "Not enough stock!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid quantity.");
    }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

  Container parent = this.getParent();
    if (parent != null) {
        parent.removeAll();
        // Pass the EXISTING dashboard reference to the SalesPanel
        parent.add(new SalesPanel(this.salesModel, this.controller, this.historyModel, this.mainDashboard), BorderLayout.CENTER);
        parent.revalidate();
        parent.repaint();
    }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
